server:
  port: 10000

spring:
  application:
    name: gateway  # 服务名 (在 nacos ui 上显示)
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #配置 Nacos 地址
    gateway:
      # 配置路由, 可以配置多个
      routes:
        - id: user_route01  # 路由id, 程序员自己指定
          # uri 是匹配后提供服务的路由地址
          # 路由请求转发的 url = uri + path, 即 http://localhost:8083/provider/user/query
          #uri: http://localhost:8083
          uri: lb://user-service-provider
          # 设置断言
          predicates:
            - Path=/provider/user/query/**
            # - After=2025-08-15T15:11:30.960+08:00[Asia/Shanghai]
            # - Before=2025-08-15T15:11:30.960+08:00[Asia/Shanghai]
            # - Between=2025-08-15T15:11:30.960+08:00[Asia/Shanghai],2025-08-16T15:11:30.960+08:00[Asia/Shanghai]
            # - Cookie=chocolate, ch.p
            # - Header=X-Key, hello
            # - Host=**.baidu2.**,**.sohu2,**
            # - Method=Get
            # - Query=email  # 带有请求参数email, 且请求值符合邮箱的正则表达式
            # - RemoteAddr=127.0.0.1
          # 设置过滤器
          filters:
            - AddRequestParameter=color,blue  #在匹配的请求头加上一对请求头，名称为color值为blue
        - id: user_route02  # 路由id, 程序员自己指定
          #uri: http://localhost:8083
          uri: lb://user-service-provider
          # 设置断言
          predicates:
            - Path=/provider/user/save
        # 配置 默认过滤器
      default-filters:
        - AddRequestParameter=key, GlobalFilter