server:
  port: 10000

spring:
  application:
    name: gateway  # 服务名 (在 nacos ui 上显示)
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #配置 Nacos 地址
    gateway:
      # 配置路由, 可以配置多个
      routes:
        - id: user_route01  # 路由id, 程序员自己指定
          # uri 是匹配后提供服务的路由地址
          # 路由请求转发的 url = uri + path, 即 http://localhost:8083/provider/user/query
          uri: http://localhost:8083
          # 设置断言
          predicates:
            - Path=/provider/user/query/**
        - id: user_route02  # 路由id, 程序员自己指定
          uri: http://localhost:8083
          # 设置断言
          predicates:
            - Path=/provider/user/save