server:
  port: 8092

spring:
  application:
    name: user-service-consumer  # 服务名 (在 eureka ui 上显示)
  profiles:
    active: dev  # 指定工作环境 dev/sit/uat/prod
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # 注册中心地址