server:
  port: 8092

spring:
  application:
    name: user-service-consumer  # 服务名 (在 eureka ui 上显示)
  profiles:
    active: dev  # 指定工作环境 dev/sit/uat/prod
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # 注册中心地址


# 使用 name 指定接口信息
#ribbon:
#  # 设置 openFeign 客户端超时时间 (openFeign 默认支持 ribbon). Tips: 这里参数的开头字母要大写.
#  ConnectTimeout: 5000  # 设置 建立连接所用的时间(两端连接所用的时间), 适用于网络状况正常的情况下.
#  ReadTimeout: 5000     # 设置 建立连接后从服务器读取到可用资源所用的时间, 默认 1s.

# 使用 url 指定接口信息
#feign:
#  client:
#    config:
#      default:  # 全局默认配置。 如果指定某个客户端, 这里就可以写为 name or contextId(客户端别名, 要在@FeignClient注解里指定)
#        connectTimeout: 5000  # 连接超时 5 秒, 默认无限等待
#        readTimeout: 5000     # 读取超时 1 秒, 默认无限等待


logging:
  level:
    # 想打印 UserWebService 接口调用过程的日志信息, 需要将日志级别设置为 debug
    com.omega.springcloud.service.UserWebService: debug
    # 如果想配置多个服务端的日志级别, 可以直接指定包的路径
    # com.omega.springcloud.service: debug


feign:
  client:
    config:
      # 默认全局配置
      default:
        loggerLevel: BASIC
      # 为特定客户端配置, 可以配置多个
      user-service-provider:  # 对应 @FeignClient 的 name 或 contextId
        loggerLevel: FULL

feign-client:
  user-service-url: http://localhost:8083/provider/user